#!/bin/bash

# SPDX-FileCopyrightText: 2013 - 2022 UnionTech Software Technology Co., Ltd.
#
# SPDX-License-Identifier: GPL-3.0-or-later

plymouthd --debug --debug-file=/tmp/plymouth-debug.log --mode='shutdown' --tty='tty3' --kernel-command-line='quiet-splash';
plymouth --show-splash;
for ((I=0; I<10; I++));
do plymouth --update=test$I;
    sleep 1;
done;
plymouth quit
